version: "3"
services:
  frontend.local:
    build: ./frontend
    ports:
      - "13001:3000"
    depends_on:
      - backend.local
    networks:
      - moi-meow-web-bookmark-network
    restart: always
  backend.local:
    build: ./backend
    volumes:
      - ./backend/public:/app/public
    ports:
      - "13002:3001"
    depends_on:
      - database
    networks:
      - moi-meow-web-bookmark-network
    restart: always
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: webBookmarkDB
      MYSQL_ROOT_PASSWORD: moimeowrootpassword
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - moi-meow-web-bookmark-network
    restart: always

networks:
  moi-meow-web-bookmark-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16